version:            "2"
services:
  antidote1:
    image:          antidotedb/antidote
    container_name: antidote1
    hostname:       antidote1
    ports:
            - 8087:8087
    environment:
      SHORT_NAME:   "true"
      NODE_NAME:    antidote@antidote1
    volumes:
      - .:/code
  antidote2:
    image:          antidotedb/antidote
    container_name: antidote2
    hostname:       antidote2
    ports:
            - 8088:8087
    environment:
      SHORT_NAME:   "true"
      NODE_NAME:    antidote@antidote2
    volumes:
      - .:/code
  antidote3:
    image:          antidotedb/antidote
    container_name: antidote3
    hostname:       antidote3
    ports:
            - 8089:8087
    environment:
      SHORT_NAME:   "true"
      NODE_NAME:    antidote@antidote3
    volumes:
      - .:/code
